AWSTemplateFormatVersion: "2010-09-09"

Description: S3 Bucket

Parameters:

  BucketName: 
    Type: String
    Default: Interview~bucket

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Ref BucketName
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
