AWSTemplateFormatVersion: "2010-09-09"

Description: S3 Bucket

Parameters:

  BucketName: 
    Type: String
    Default: JoeWraggDevopsInterviewBucket

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Ref BucketName
      DeletionPolicy: Retain
      UpdateReplacePolicy: Retain
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  S3BucketArn:
    Description: The ARN of the S3 bucket
    Value: !GetAtt S3Bucket.Arn